[package]
name = "unicode_title_case"
version = "0.1.0"
edition = "2021"
authors = ["Carl Raffaele"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Teh-Bobo/unicode-title-case"

[features]
default = ["std"]
std = []